FROM grafana/grafana:latest


RUN grafana-cli plugins install grafana-piechart-panel \
    && grafana-cli plugins install grafana-clock-panel \
    && grafana-cli plugins install grafana-simple-json-datasource


