openapi: 3.0.0
info:
  title: API de Gestão de Pagamentos
  version: 1.0.0
  description: Endpoints para gerenciamento de pagamentos escolares

paths:
  /pagamentos:
    post:
      summary: Registra um novo pagamento
      description: Cria um novo registro de pagamento associado a um aluno
      tags:
        - Pagamentos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PagamentoInput'
      responses:
        '201':
          description: Pagamento registrado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Pagamento adicionado"
                  id_pagamento:
                    type: integer
                    example: 1
        '400':
          description: Campos obrigatórios faltando
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Campos obrigatórios não preenchidos"
        '404':
          description: Aluno não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Aluno não encontrado"
        '500':
          description: Erro interno do servidor

  /pagamentos/{id_pagamento}:
    get:
      summary: Obtém detalhes de um pagamento
      description: Retorna informações completas de um pagamento específico
      tags:
        - Pagamentos
      parameters:
        - name: id_pagamento
          in: path
          required: true
          description: ID do pagamento
          schema:
            type: integer
      responses:
        '200':
          description: Dados do pagamento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pagamento'
        '404':
          description: Pagamento não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Pagamento não encontrado"
        '500':
          description: Erro interno do servidor

    put:
      summary: Atualiza um pagamento existente
      description: Modifica os dados de um pagamento registrado
      tags:
        - Pagamentos
      parameters:
        - name: id_pagamento
          in: path
          required: true
          description: ID do pagamento
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PagamentoUpdate'
      responses:
        '200':
          description: Pagamento atualizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Pagamento atualizado"
        '404':
          description: Pagamento não encontrado
        '500':
          description: Erro interno do servidor

    delete:
      summary: Remove um pagamento
      description: Exclui permanentemente um registro de pagamento
      tags:
        - Pagamentos
      parameters:
        - name: id_pagamento
          in: path
          required: true
          description: ID do pagamento
          schema:
            type: integer
      responses:
        '200':
          description: Pagamento removido com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Pagamento deletado"
        '404':
          description: Pagamento não encontrado
        '500':
          description: Erro interno do servidor

components:
  schemas:
    PagamentoInput:
      type: object
      required:
        - id_aluno
        - valor
        - data_pagamento
        - metodo_pagamento
      properties:
        id_aluno:
          type: integer
          description: ID do aluno associado
          example: 1
        valor:
          type: number
          format: float
          description: Valor do pagamento
          example: 350.50
        data_pagamento:
          type: string
          format: date
          description: Data do pagamento (YYYY-MM-DD)
          example: "2023-10-20"
        metodo_pagamento:
          type: string
          description: Método de pagamento utilizado
          example: "PIX"
        referencia:
          type: string
          description: Código de referência/transação
          example: "PIX12345"
          default: ""
        status:
          type: string
          description: Status do pagamento
          example: "pendente"
          default: "pendente"

    PagamentoUpdate:
      type: object
      required:
        - id_aluno
        - valor
        - data_pagamento
        - metodo_pagamento
      properties:
        id_aluno:
          type: integer
        valor:
          type: number
          format: float
        data_pagamento:
          type: string
          format: date
        metodo_pagamento:
          type: string
        referencia:
          type: string
        status:
          type: string
          enum: [pendente, processando, concluído, cancelado]

    Pagamento:
      type: object
      properties:
        id_pagamento:
          type: integer
          description: ID único do pagamento
          example: 1
        id_aluno:
          type: integer
          example: 1
        data_pagamento:
          type: string
          format: date
          example: "2023-10-20"
        valor:
          type: number
          format: float
          example: 350.50
        metodo_pagamento:
          type: string
          example: "PIX"
        referencia:
          type: string
          example: "PIX12345"
        status:
          type: string
          example: "concluído"