version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: sistema_escolar_db
    restart: always
    environment:
      POSTGRES_DB: escola_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - dados_escola:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

volumes:
  dados_escola: