--a tabela aluno representa os estudantes da escola
CREATE TABLE "aluno" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_completo" varchar(255),
  "data_nascimento" date,
  "endereco" varchar(255),
  "contato_responsavel" varchar(100),
  "matricula" varchar(50) UNIQUE
);
--a tabela professor representaos professores a materia que ele é responsavel e seus dados
CREATE TABLE "professor" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_completo" varchar(255),
  "especialidade" varchar(100),
  "contato" varchar(100),
  "registro_profissional" varchar(50) UNIQUE
);
--disciplina as materias oferecidas na escola e o codigo de cada uma para ficar mais facil de serem identificadas no sistema 
CREATE TABLE "disciplina" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100),
  "codigo" varchar(50) UNIQUE,
  "carga_horaria" int
);
--serve para fazer o relacionamentoentre disciplinas e professores e o ano letivo.
CREATE TABLE "turma_disciplina" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "disciplina_id" int,
  "professor_id" int,
  "ano_letivo" int
);
--controla a matricula dos alunos em turmas
CREATE TABLE "matricula_turma" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "aluno_id" int,
  "turma_id" int,
  "data_matricula" date
);
--serve para registrar o desempenho e o historico do aluno(boletim)
CREATE TABLE "nota_frequencia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "aluno_id" int,
  "disciplina_id" int,
  "nota" decimal(5,2),
  "frequencia" decimal(5,2)
);

ALTER TABLE "turma_disciplina" ADD FOREIGN KEY ("disciplina_id") REFERENCES "disciplina" ("id");

ALTER TABLE "turma_disciplina" ADD FOREIGN KEY ("professor_id") REFERENCES "professor" ("id");

ALTER TABLE "matricula_turma" ADD FOREIGN KEY ("aluno_id") REFERENCES "aluno" ("id");

ALTER TABLE "matricula_turma" ADD FOREIGN KEY ("turma_id") REFERENCES "turma_disciplina" ("id");

ALTER TABLE "nota_frequencia" ADD FOREIGN KEY ("aluno_id") REFERENCES "aluno" ("id");

ALTER TABLE "nota_frequencia" ADD FOREIGN KEY ("disciplina_id") REFERENCES "disciplina" ("id");

/*Aluno X Turma_Disciplina: relação N:N via Matricula_Turma. um aluno pode estar matriculado em apenas uma turma
Aluno X Disciplina: relação indireta via Nota_Frequencia, permitindo múltiplos registros por disciplina/ano. um aluno pode fazer varias disciplinas e ter varias notas e frequencias.
Professor X Disciplina: através da Turma_Disciplina, associando disciplinas e professores por ano. O professor pode dar aula para varias turmas, mas ter apenas uma disciplina*/ 